### PR TITLE
Rebrand alignment

### PR DESCRIPTION
**Pull request by emdecr**
This PR covers the application of the new branding to developers.mattermost.com

This includes:
- Replacing the nav with the one used on mattermost.com
- Redesign of homepage
- Application of new fonts and colour palette

### CODE REVIEW

**Comment by emdecr** [comment]
@cwarnermm Hi Carrie – just a heads up that I opened this draft PR, so folks can start looking around at the changes.
There's still a bunch of tweaks to made.

TY~!

**Comment by cwarnermm** [comment]
Thanks, @emdecr! My first peek at the rebranded site looks fantastic!!

**Comment by emdecr** [comment]
@cwarnermm This PR should be good to go for a review now. I've re-synced things 

A few things to note: 

- These changes only cover stylistic changes as mentioned in a previous comment
- As discussed in a previous R&D meeting (by Ashley), we will be migrating the blog content to the main mm.com blog
- A subsequent PR will be made to handle the actual redirects for the blog area - ie. the blog area and posts will still be available to link to for dev.mm.com for now, but will eventually (to my understanding) be redirected to their mm.com/blog equivalents
- Said subsequent PR will also include some clean up – there's some legacy code still up there that we can purge now that we've rebranded everything

I'm still not sure about how to go about external redirects for Hugo sites, I know focalboard.com using soft redirects via javascript, which is what we could do, but I'm open to opinions. 

As always, let me know if there's any questions - thanks!

**Comment by cwarnermm** [comment]
@emdecr - The dev site looks so GOOD! WOW! Great job!!! 

On the topic of Hugo redirects: I have discovered a [Hugo forum](https://discourse.gohugo.io/) that may prove helpful. On that forum, there's a thread about [redirecting external pages](https://discourse.gohugo.io/t/how-can-i-redirect-to-an-external-link-on-click-of-header-of-any-blog/9886).

@hanzei - Do you have experience setting up external redirects for Hugo sites? Or can point us towards resources we can learn from, perhaps?

**Comment by emdecr** [comment]
@cwarnermm I JUST caught that I forgot to apply the nav changes to the internal pages – but should be good now. Sorry about that 😅

Thanks for the help with the redirects. I'll look at those resources and keep looking as well.

**Review by cwarnermm — APPROVED** [review]
This rebrand alignment looks so clean and fresh! Quick note: This PR appears to be a WIP, which means it can't yet be merged.

Also, FYI only: I stumbled upon a broken image on [this page](https://developers.mattermost.com/integrate/admin-guide/admin-interactive-messages/#message-menus), but it wasn't caused by this PR since it also appears in Production. We'll address this issue separately.

**Comment by emdecr** [comment]
> This rebrand alignment looks so clean and fresh! Quick note: This PR appears to be a WIP, which means it can't yet be merged.
> 
> Also, FYI only: I stumbled upon a broken image on [this page](https://developers.mattermost.com/integrate/admin-guide/admin-interactive-messages/#message-menus), but it wasn't caused by this PR since it also appears in Production. We'll address this issue separately.

@cwarnermm Thanks so much as always for the review! 🙌 
I have removed the WIP tag and will remember to do so going forward (hopefully haha).

As mentioned before, I will follow up with a subsequent PR - hopefully in the next few weeks - that will address some clean up of css/template bloat, and discuss next steps for the migration of the blog posts to mattermost.com/blog. [We already have the posts in draft mode](https://docs.google.com/spreadsheets/d/18niasyj1TXZ1hWZ7nIhUHpOuEKEGFjcR4TmFLm8HtuQ/edit?usp=sharing), but we need to migrate images to our database and make sure everything's ported over correctly/fully.

**Comment by cwarnermm** [comment]
@BenLloydPearson - We need a second reviewer on this PR for this repository. Would you do us the honours, please?

**Review by BenLloydPearson — APPROVED** [review]
Great work as always, @emdecr!

**Pull request merged**
