### PR TITLE
Update contribution guidelines

### PR DESCRIPTION
**Pull request by jwilander**
Also removed empty page + minor update to paragraph spacing.

### CODE REVIEW

**Comment by jwilander** [comment]
Yeah I was thinking about that as well, but I do think there is a good chunk that would be shared between all of them

We can probably re-org the whole thing a bit to make it work with having some info here and specific info in the other sections

**Comment by jasonblais** [comment]
> We can probably re-org the whole thing a bit to make it work with having some info here and specific info in the other sections

Should I create a separate ticket for it?

**Comment by jwilander** [comment]
@jasonblais yes please, that way this PR won't go stale and we can merge it

**Comment by jasonblais** [comment]
Thanks, I meant to come back to this and review.

Made a couple of minor tweaks https://github.com/mattermost/mattermost-developer-documentation/pull/61/commits/00d161795d3bdbb924463bfc757717783addedc4

**Pull request merged**
