### PR TITLE
Update core-committers.md

### PR DESCRIPTION
**Pull request by andrewbrown00**
Adding a 'Product Designers' section

### CODE REVIEW

**Comment by andrewbrown00** [comment]
I'm pretty sure I signed the CLA agreement when I started, but I signed it again just in case.

**Comment by lieut-data** [comment]
@andrewbrown00, heads up that @justinegeffen relocated this documentation to the handbook.

**Comment by justinegeffen** [comment]
Thanks, @lieut-data! I don't think the PR has been merged yet, hence the confusion. Let me get that sorted.

**Comment by justinegeffen** [comment]
Just re-checked and I can confirm that the live version contains a redirect to the Handbook page. @andrewbrown00, I'm going to close this PR and update the Handbook if that's alright with you?

**Comment by andrewbrown00** [comment]
Thanks, @lieut-data and @justinegeffen! I also let Lynn know so we can update the onboarding task which has "this" old link.

**Pull request closed without merging**
