### PR TITLE
Change title of iouring blog post

### PR DESCRIPTION
**Pull request by agnivade**
#### Summary

Right now, it gives the impression that the post gets hands-on with Go also. We fix that.

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thanks, @agnivade. Great catch, it reads better now. :) I didn't know who to add for the second approving review but it LGTM. :)

**Comment by agnivade** [comment]
It's a one word change, so one reviewer is fine :)

**Comment by agnivade** [comment]
Thanks @isacikgoz

**Pull request merged**
