### PR TITLE
SEO Updates - Url Corrections Missing Terminating Slash

### PR DESCRIPTION
**Pull request by lawrencejohnson**
#### Summary
Per SEO request to remove daisy chained links, internal URLs were examined and found to have numerous links that were missing a trailing slash. This causes a redirect response every time a visitor hits those links, so the existing content was explored referencing a report indicating pages with bad links and updates were applied.

#### Ticket Link
https://mattermost.atlassian.net/browse/MAR-187

### CODE REVIEW

**Review by hanzei — APPROVED** [review]

**Review by jaydeland — COMMENTED** [review]
Lgtm

**Comment by jfrerich** [comment]
@jaydeland, I think you accidentally left your message as a comment instead of a PR approval.  Can you verify, approve, and merge if that's correct? Thanks!

**Review by jaydeland — APPROVED** [review]

**Comment by jaydeland** [comment]
> @jaydeland, I think you accidentally left your message as a comment instead of a PR approval. Can you verify, approve, and merge if that's correct? Thanks!
Sorry about that - I was using a mobile client at the time.

**Pull request merged**
