### PR TITLE
Update footer.html

### PR DESCRIPTION
**Pull request by AugustinJose1221**
#### Summary

Added <a> tag attribute to open social media accounts in a new window.

### CODE REVIEW

**Review by hanzei — APPROVED** [review]

**Review by justinegeffen — APPROVED** [review]

**Comment by AugustinJose1221** [comment]
The cla check has failed. I'm not much familiar with its workflow. So can anyone tell how to complete the cla check for this PR?

**Comment by hanzei** [comment]
That did the trick :wink:

**Comment by hanzei** [comment]
Thanks for the quick fix @AugustinJose1221 :+1:

**Pull request merged**
