### PR TITLE
Minor typo in Step 1 fix

### PR DESCRIPTION
**Pull request by stevemudie**
#### Summary
There was an extra "keys." after the end of the sentence in the first step.

This edit removes it.

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thank you, @stevemudie!

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
@stevemudie, thank you! Please let me know when you've signed the CLA and we can merge this. :)

**Pull request merged**
