### PR TITLE
Update windows.md  change 'export' to 'set' for setting environment variables

### PR DESCRIPTION
**Pull request by allenlai18**
https://stackoverflow.com/questions/18701783/windows-equivalent-of-export

### CODE REVIEW

**Comment by allenlai18** [comment]
it should be 'set' in windows rather than 'export'   to set environment variables

**Comment by allenlai18** [comment]
how do i rerun the check. i signed the CLA

**Comment by hanzei** [comment]
@svelle Could you please review this?

**Comment by svelle** [comment]
using export is technically correct here since we refer to using babun, however babun has been discontinued and we should provide an alternative for setting up the server environment on windows if we want to keep it in the documentation.

**Pull request closed without merging**
