### PR TITLE
update vault documentation

### PR DESCRIPTION
**Pull request by cpanato**

### CODE REVIEW

**Comment by amyblais** [comment]
@cpanato Is this WIP or ready for review?

**Comment by cpanato** [comment]
yes @amyblais

**Comment by jwilander** [comment]
I will try the new instructions today

**Comment by jwilander** [comment]
Tested and it worked for me. @cpanato can you give me a quick summary as to the reason for the update?

**Comment by cpanato** [comment]
There is a bug in the sshd which vault is using and the workaround for that is generating this `ed25519` which is more security as well (as bonus). and then we need to update this doc to reflect the new usage

**Pull request merged**
