### PR TITLE
Update 404.html

### PR DESCRIPTION
**Pull request by emdecr**
#### Summary
This PR adds markup to the 404 template, so we can use it for our custom error response.

To view template: visit `/404.html`

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54776

### CODE REVIEW

**Comment by emdecr** [comment]
@iyampaul for visibility

**Comment by cwarnermm** [comment]
@emdecr - Looks like one of the merge checks includes running some kind of HTML check that's [failing](https://github.com/mattermost/mattermost-developer-documentation/actions/runs/6500037200/job/17654599556?pr=1299). This is the first time I've seen these errors, and I'm not sure how many, if any, we can safely ignore.

**Comment by emdecr** [comment]
@cwarnermm Haha – maybe this is why it was empty 😁 Works locally when you visit http://localhost:1313/404.html, but lemme look around to address errors.

**Comment by emdecr** [comment]
Oh whoa – that was a doozy. Thanks to @azigler for helping me debug while on our sync 😂 

For breadcrumb purposes: Something to note is that whatever is looking at this specific template is super strict on formatting. Feels like things get encoded differently. Does not like spaces or white space. The partials that would normally work on any other page, throw errors during build.

I think we're okay now 🤞

**Review by azigler — APPROVED** [review]
Fun troubleshooting today on our call!

**Review by cwarnermm — APPROVED** [review]

**Comment by cwarnermm** [comment]
@emdecr - Please feel free to merge this in whenever you're ready.

**Pull request merged**
