### PR TITLE
Add a new sample plugin to dev docs site

### PR DESCRIPTION
**Pull request by jasonblais**

### CODE REVIEW

**Comment by ccbrown** [comment]
The documentation looks good to me, but that plugin really isn't an example at all. You can't easily look at the source code, and even if you did, you wouldn't find anything at all relevant to plugin development since it uses a very different mechanism.

Is there somewhere else we can put this? Alternatively, maybe we should just prioritize porting this plugin to the RPC mechanism like the others.

**Comment by jasonblais** [comment]
@ccbrown Hm, yeah. Good point. Maybe I should add it to our docs.mattermost.com page instead? Since it's really meant for admins rather than developers.

**Comment by ccbrown** [comment]
Makes sense to me.

**Comment by jasonblais** [comment]
PR in docs: https://github.com/mattermost/docs/pull/1754/

**Pull request closed without merging**
