### PR TITLE
Update Twitter logo in footer

### PR DESCRIPTION
**Pull request by emdecr**
#### Summary
This PR updates the Twitter/X logo in the footer. TY!

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thanks, @emdecr!

**Review by nat-gunner — COMMENTED** [review]
@emdecr We should probably update the `<title>` element to "X icon" (or maybe "X social network icon" since X is a terribly undescriptive name...)

**Comment by emdecr** [comment]
@nat-gunner Good flag - I think `X icon` works 👍 

@cwarnermm I'll make the same switch to docs.mm.com in an upcoming PR for Hacktoberfest.

**Review by nat-gunner — APPROVED** [review]
@emdecr thanks!

**Review by azigler — APPROVED** [review]
Looks good!

**Pull request merged**
