### PR TITLE
Update notification banner and global nav

### PR DESCRIPTION
**Pull request by emdecr**
#### Summary
This PR adds the 9.0 announce blog to the notification banner, and updates the global nav to align with mm.com.

@cwarnermm – Feel free to adjust the footer links and I'll mirror the changes on mm.com. Will add more reviewers once we're zipped up.

Thank you!

### CODE REVIEW

**Comment by cwarnermm** [comment]
@emdecr - Let's apply the 2 header updates proposed via x:

- Let's update the Academy link to point to: ``https://academy.mattermost.com/``
- Let's update the Release Notes link to: ``https://docs.mattermost.com/guides/changelogs.html``

And just to confirm, the dev docs site footer is far simpler than the docs footer intentionally?

**Comment by emdecr** [comment]
@cwarnermm Yep – I don't think there's ever been a footer mirror (of docs/mm.com) on this site since I've been here.

**Comment by emdecr** [comment]
@nat-gunner For review - nav changes for 9.0 - TY!

**Comment by cwarnermm** [comment]
@emdecr - phew! For a moment I thought I was mis-remembering one! :)

**Review by nat-gunner — APPROVED** [review]
looks good!

**Review by cwarnermm — APPROVED** [review]
Thank you, @emdecr!!

**Pull request merged**
