### PR TITLE
REST API Docs: Fix syntax error in Go code sample and indent

### PR DESCRIPTION
**Pull request by zefhemel**
Hey, first time committer here (starting my new job at MatterMost from March, but already warming up).

#### Summary
I noticed a syntactical error in the Go example on adding API endpoints, this fixes it. Bonus: it indents the comments.

#### Ticket Link
No ticket, didn't seem worth it since it's a trivial fix.

### CODE REVIEW

**Comment by zefhemel** [comment]
FYI I signed the CLA a few minutes before submitting the PR.

**Review by hanzei — APPROVED** [review]
LGTM

**Review by larkox — APPROVED** [review]

**Pull request merged**
