### PR TITLE
Fix "We're hiring" banner permalink issue and markdown table word wrap

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR fixes the issue where you click on a permalink for a paragraph within the page, and the page scrolls to the paragraph, but the "We're hiring" banner overlaps the top of the linked section. Now there is a spacing used for positioning the content below the banner, taking the height of banner into account.

This PR also fixes an issue where markdown table columns had undesired word wrap. The solution used is "for any code block that is in the first column of a table, do not allow word wrap."

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/739

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM :+1:

**Comment by mickmister** [comment]
The changes don't seem to have worked in the preview environment https://mattermost.github.io/mattermost-developer-documentation/857/integrate/apps/call/#expand. The permalinks are still getting overlapped by the banner, and the table cell is still wrapping

**Comment by hanzei** [comment]
@mickmister Jep, the preview is broken.

**Review by michelengelen — APPROVED** [review]
LGTM

**Pull request merged**
