### PR TITLE
/contribute Redirect

### PR DESCRIPTION
**Pull request by BenLloydPearson**
#### Summary
Redirect /contribute to /contribute/getting-started

#### Ticket Link
Based on Discussion with @cwarnermm

### CODE REVIEW

**Comment by BenLloydPearson** [comment]
Note: This PR doesn't actually work. There appears to be a bug or misconfiguration that prevents redirects from working with the /contribute page. See #1023

**Comment by lieut-data** [comment]
@BenLloydPearson & @cwarnermm, I've pushed something that appears to work locally for me. Can you take a look?

**Comment by cwarnermm** [comment]
@lieut-data The latest site preview is redirecting as expected!! Thanks so much!!! @BenLloydPearson Can you also confirm that Jesse's update is working as you'd expect?

**Review by cwarnermm — APPROVED** [review]
Thank you @lieut-data!!

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
