### PR TITLE
Document cherry-pick process

### PR DESCRIPTION
**Pull request by amyblais**

### CODE REVIEW

**Comment by amyblais** [comment]
I've been approached already by a few new devs because they were confused about how to cherry-pick a PR.

Can somebody help add the step-by-step process of how PRs are cherry-picked to a release?

@grundleborg / @enahum / @jwilander or somebody else

**Comment by crspeller** [comment]
Current documentation of process is here: https://docs.google.com/presentation/d/1cxCIDaTLv_GQ3_L4u-hIrstkFLj_umRlUsZwsW-7ZdQ

I can make some time to move the documentation here.

**Comment by amyblais** [comment]
Closing, opened a task ticket for Christopher: https://mattermost.atlassian.net/browse/MM-16298

**Comment by crspeller** [comment]
@amyblais Thanks! I should know stuff doesn't get done without tickets :P

**Pull request closed without merging**
