### PR TITLE
JS quickstart: formatting and new step

### PR DESCRIPTION
**Pull request by justinegeffen**
- hello-world > helloworld
- Added uninstall step

### CODE REVIEW

**Review by mickmister — COMMENTED** [review]
Should this step be added to the go quick start doc? Also maybe there's a way we can share snippets between the files like this? I'm not sure how that works

**Comment by mickmister** [comment]
Oh I see it's added at https://github.com/mattermost/mattermost-developer-documentation/pull/819. Maybe make it into one PR?

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
> Maybe make it into one PR?

nvm it's fine how it is :+1:

**Review by hanzei — APPROVED** [review]

**Comment by justinegeffen** [comment]
@mickmister, great question about snippets. So we can do that in our docs repo using Sphinx using `include:` and we do have common content that we share like that. But I'm not certain whether Hugo supports that. I'll investigate. :)

**Pull request merged**
