### PR TITLE
Update core-committers.md

### PR DESCRIPTION
**Pull request by justinegeffen**
Minor adjustments of offboarded staff.

Note:
** The structure of this page is not aligned to teams/verticals. One option is to organize into functional areas. Another is to organize it under a larger umbrella "Engineers", "Product Managers" etc and just list specializations/verticals per person. 
** IMO this should be moved into the Engineering section of the Handbook. Once the content/structure is agreed-on, I can do that.

### CODE REVIEW

**Review by jasonblais — APPROVED** [review]
Approving PM and tech writer sections

**Comment by lieut-data** [comment]
@justinegeffen, I've pushed a few additional changes both to the list of core committers, as well as minor tweaks to the r&d teams to reflect the same changes. That page, of course, needs a more holistic overhaul to reflect the teams as they exist today.

**Review by lieut-data — APPROVED** [review]

**Comment by jwilander** [comment]
@justinegeffen I pushed a commit that updates the R&D teams structure to match the new org. Hopefully that's ok with you :)

**Review by jwilander — APPROVED** [review]

**Review by lieut-data — APPROVED** [review]

**Comment by justinegeffen** [comment]
Thank you so much, @jwilander and @lieut-data! The changes are awesome, I really appreciate your help. :)

**Comment by justinegeffen** [comment]
@jasonblais, once this is approved and merged I'll move this over to the Handbook for better visibility.

**Pull request merged**
