### PR TITLE
add dev setup for ubuntu 18.04

### PR DESCRIPTION
**Pull request by cpanato**
Add Dev setup steps for the new ubuntu 18.04

### CODE REVIEW

**Comment by jwilander** [comment]
@cpanato good for review?

**Comment by cpanato** [comment]
@jwilander yes

**Comment by hanzei** [comment]
@cpanato From what I can see the only difference to the Ubuntu 16.04 guide is the use of `apt` instead of `apt-get`. But `apt-get` is available on Ubuntu 18.04.

Are there other differences? Why do we need this guide?

**Comment by cpanato** [comment]
@hanzei yes, i was thinking about that and maybe is better just update the tab name to add `Ubuntu 16.04/18.04`
thanks for the feedback

**Comment by cpanato** [comment]
done @hanzei

**Pull request merged**
