### PR TITLE
updated vault.md with instructions on loadtesting

### PR DESCRIPTION
**Pull request by reflog**
Added some `ltops` related notes

### CODE REVIEW

**Comment by reflog** [comment]
@DSchalla - why not both? Mostly for visibility...

**Comment by DSchalla** [comment]
Mostly the concern that both needs to be maintained, and that this information is not particular useful to an outside contributor. The `internal` directory of the dev docs are in my opinion (this was discussed a few times in the past...) a bad split between "We don't want this to be public, but also not properly private" which we try to avoid. Change itself looks great and is a great addition.

**Comment by reflog** [comment]
Ok. Will close this and add to the internal docs

**Comment by DSchalla** [comment]
Thanks @reflog, appreciate it!

**Comment by hanzei** [comment]
@DSchalla What is the reason that the `internal` docs still exist? Can't we just move everything to https://github.com/mattermost/internal-docs/?

**Comment by DSchalla** [comment]
Absolutely. We are still migrating the content and adding additional documentation, but that's the goal overall.

**Pull request closed without merging**
