### PR TITLE
update team page

### PR DESCRIPTION
**Pull request by hannaparks**
update team page

### CODE REVIEW

**Comment by hanzei** [comment]
@hannaparks Who would be a good person to review this?

**Comment by hannaparks** [comment]
> @hannaparks Who would be a good person to review this?

How about you @hanzei ?

**Comment by hanzei** [comment]
Where does this data come from? Is it created automatically or manually?

**Comment by hannaparks** [comment]
@hanzei it's from the list you used to provide Lindy and me with but yes this part on updating the team page is very manual.  I add all the names in here per repo alphabetically.  I think @cpanato merges the MVP page, maybe he can do this one too?

**Comment by cpanato** [comment]
@hannaparks please sign the CLA :)

I can review but actually anyone can do that as well

**Comment by hannaparks** [comment]
TY

**Pull request merged**
