### PR TITLE
Zapier integration

### PR DESCRIPTION
**Pull request by josephjosedev**
Zapier integration index file updated

### CODE REVIEW

**Review by neflyte — APPROVED** [review]
Thanks for your contribution, @josephjosedev!
We'll get more reviewers assigned to this for approvals. :smile:

**Review by cwarnermm — APPROVED** [review]
Thank you so much, @josephjosedev!

**Comment by josephjosedev** [comment]
:joy: its quite interesting

**Comment by josephjosedev** [comment]
@justinegeffen

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
