### PR TITLE
Wrong Golang Link In WSL Setup

### LINKED ISSUE #1158: Wrong Golang Link In WSL Setup
In the [**_Setting Up Your Development Environment_**](https://developers.mattermost.com/contribute/more-info/server/developer-setup/) page, under the **Windows WSL** section, when you get to step 4, it states:

> Install Go using bash (modify installation to latest Go version from https://golang.org/dl/):

This link does not work anymore and should be rewritten to https://go.dev/dl/.

### PR DESCRIPTION
**Pull request by TomerPacific**
#### Summary
In the [Setting Up Your Development Environment](https://developers.mattermost.com/contribute/more-info/server/developer-setup/) page, under the Windows WSL section, when you get to step 4, it states:

> Install Go using bash (modify installation to latest Go version from https://golang.org/dl/):

This link does not work anymore and I changed it to https://go.dev/dl/.

#### Ticket Link
  Fixes #1158

### CODE REVIEW

**Comment by neflyte** [comment]
Thanks for your contribution, @TomerPacific!

**Review by neflyte — APPROVED** [review]

**Comment by TomerPacific** [comment]
@neflyte, should I tag another member to review this?

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
