### PR TITLE
Update Arch developer setup instructions

### PR DESCRIPTION
**Pull request by sparr**
#### Summary

Correct some commands and add more optional steps for setting up the developer environment on Arch Linux (and forks)

### CODE REVIEW

**Comment by sparr** [comment]
I am not sure how to get from the preview environment link to the page that shows this content which is https://developers.mattermost.com/contribute/more-info/desktop/developer-setup/ on the live site

**Comment by cwarnermm** [comment]
Hi @sparr - To review your changes in the generated preview, use the file path of the page you modified as a guide: ``/contribute/more-info/desktop/developer-setup/arch.md`` > Contribute > More Info > Desktop app > Developer Setup > Arch tab.

**Comment by sparr** [comment]
Thank you. The page in the preview environment looks how I expect.

**Review by devinbinnie — APPROVED** [review]
LGTM! Thanks @sparr!

**Review by cwarnermm — APPROVED** [review]
Thank you, @sparr!

**Pull request merged**
