### PR TITLE
fix small typo

### PR DESCRIPTION
**Pull request by dfun90**
#### Summary

Fixed a small typo `boo` to `bool`

#### Ticket Link

Not applicable.

### CODE REVIEW

**Review by hanzei — APPROVED** [review]

**Comment by hanzei** [comment]
@dfun90 It seems like you entered the wrong user name when signing the CLA. Would you be open on signing it again with `dfun90`?

**Comment by dfun90** [comment]
> @dfun90 It seems like you entered the wrong user name when signing the CLA. Would you be open on signing it again with `dfun90`?

Hey, yea, I noticed it myself the other day and wrote an email to the Mattermost team asking them to fix it, but I just signed another CLA with the correct username.

**Review by cwarnermm — APPROVED** [review]
Thanks!

**Pull request merged**
