### PR TITLE
Transform page references to Hugo templated references

### PR DESCRIPTION
**Pull request by neflyte**
#### Summary

Page references in the Integrate and Contribute sections were transformed into Hugo templated references. This allows for consistent linking between pages and ensures links aren’t hard-coded to a particular base URL.

##### Notes
- This PR is based on #1095 which refactored the site layout. Please ignore the layout refactoring changes when reviewing.
- #1095 must merge before this PR merges.
- This PR resolves #1094

### CODE REVIEW

**Review by justinegeffen — APPROVED** [review]
This is awesome work, thanks so much! :)

**Review by cwarnermm — APPROVED** [review]
Thanks, @neflyte!

**Comment by cwarnermm** [comment]
We'll merge this approved PR once https://github.com/mattermost/mattermost-developer-documentation/pull/1095 is merged.

**Pull request merged**
