### PR TITLE
Adding vipul08 to contributor wall of fame

### PR DESCRIPTION
**Pull request by jasonblais**
Attached is the addition

image

@emilyacook this would be a good list to automate (not time-sensitive).

### CODE REVIEW

**Review by emilyacook — APPROVED** [review]

**Comment by emilyacook** [comment]
> Attached is the addition
> 
> image
> 
> @emilyacook this would be a good list to automate (not time-sensitive).

Noted!

**Comment by jasonblais** [comment]
@amyblais just needs a second reviewer to merge,

**Review by amyblais — APPROVED** [review]

**Pull request merged**
