### PR TITLE
Add best practices and Hugo shortcodes to README.md

### PR DESCRIPTION
**Pull request by neflyte**
#### Summary
This PR updates `README.md` to:

- Improve environment setup instructions
- Add some best practices
- Document the available Hugo shortcodes

To view the updated `README.md` from this PR, visit [this link](https://github.com/neflyte/mattermost-developer-documentation/tree/nef-docs-best-practices).

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thank you, @neflyte!

@justinegeffen - The developer documentation guidance is currently being proposed for the repository's README file. Looking forward to your feedback on whether this is the ideal home for this type of content.

**Review by asatkinson — APPROVED** [review]
Approved.  I tried everything except the mermaid tags.  A couple of nitpics
- After step 2 of the install, you need to cd mattermost-developer-documentation.  Perhaps goes without saying tho.
- Having go installed and setup is a prerequisite.  Perhaps assumed - though some hopefully we start getting JS people without golang experience soon!

**Comment by neflyte** [comment]
@asatkinson I will fix those issues; they're important for the success of contributors.

**Review by justinegeffen — APPROVED** [review]
This is an awesome update, thank you!

**Review by cwarnermm — APPROVED** [review]
Thanks, @neflyte!

**Review by azigler — APPROVED** [review]
Really great PR! Thank you for standardizing this, I agree with the input thus far and think the README is in great shape.

**Review by hanzei — APPROVED** [review]
Excellent work, Alan :tada:

**Pull request merged**
