### PR TITLE
Fix broken links in contribute/server/developer-setup section

### PR DESCRIPTION
**Pull request by neflyte**
#### Summary

Fixed broken links in the `/contribute/server/developer-setup` section due to malformed Markdown syntax. The front matter for the affected pages was modified to be consistent with YAML as it is used in the rest of the site.

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thanks, @neflyte!

**Review by azigler — COMMENTED** [review]
Hey @neflyte, thanks for this PR! I'm not sure I'm seeing the desired outcome on my end. Looks like changing these headers broke the formatting. Ex: http://mattermost-dev-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/1102/contribute/server/developer-setup/ cc @cwarnermm 
image

**Comment by neflyte** [comment]
@azigler I only caught this locally after refreshing the page a couple times. :wink:
What's happening is the included content doesn't have its frontmatter removed before it's displayed. This is a known issue with Hugo. Luckily there are various solutions around; I was able to resolve this using a solution that simply removes the frontmatter.

I'll make that fix and test a few more pages.

**Comment by neflyte** [comment]
Even better: I don't need to fix how the content is included as I simply removed the frontmatter from that set of included content. The frontmatter, it turns out, exposes the page in the LHS as well and that's undesired in this case.

For reference, there are 2 sections that import content from other files:
- `/contribute/server/developer-setup`
- `/contribute/desktop/developer-setup`

**Review by azigler — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
