### PR TITLE
Update labels page with new label and updated links

### PR DESCRIPTION
**Pull request by justinegeffen**
Update to fix https://github.com/mattermost/mattermost-handbook/issues/80

### CODE REVIEW

**Review by jasonblais — DISMISSED** [review]
Minor formatting fixes

**Review by cwarnermm — APPROVED** [review]
Thanks!

**Comment by justinegeffen** [comment]
Thanks for the feedback, @jasonblais!

**Review by BenLloydPearson — APPROVED** [review]
I'll approve this to help merge it, but generally speaking, I'm happy to let y'all manage the specifics of label usage. So, I don't have super strong opinions about what labels are included here. My concerns are mostly related to the overall structure and digestibility of the page.

**Review by jasonblais — APPROVED** [review]

**Pull request merged**
