### PR TITLE
Changed the links with the updated ones

### PR DESCRIPTION
**Pull request by DaKeiser**
Fixes Issue #401 
Updated the links as mentioned in the above issue.

### CODE REVIEW

**Comment by amyblais** [comment]
@DaKeiser Sorry, it looks like there is already a PR open here for this: https://github.com/mattermost/mattermost-developer-documentation/pull/409.

**Comment by DaKeiser** [comment]
> @DaKeiser Sorry, it looks like there is already a PR open here for this: #409.

But I guess this was assigned to me, so I sent a PR.

**Comment by DaKeiser** [comment]
I guess I was assigned this PR. So I sent it. I'm sorry for the conflict @amyblais

**Comment by hanzei** [comment]
Oh, sorry @DaKeiser. I messed up the naming. Sorry agian.

**Pull request closed without merging**
