### PR TITLE
Removed unnecessary commas in JSON examples

### PR DESCRIPTION
**Pull request by Peytob**
Some of the commas provided in the sample JSON objects broke the json syntax. The commas have been removed.

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
Thanks for this fix @Peytob :+1:

Looks like there are stilol some issues with the CLA. Have you made sure to have it signed?

**Review by cwarnermm — APPROVED** [review]
Thanks, @Peytob! Really appreciate your eye for detail!

**Comment by Peytob** [comment]
@mickmister Yesterday I forgot to sign the CLA. Now I signed it, but /check-cla didn't do anything. After signing, I received an email attached to the message.
It seems to me that I did not do all the necessary steps. What could I forget?
image

**Comment by mickmister** [comment]
Awesome, thanks @Peytob!

**Pull request merged**
