### PR TITLE
[MM-35160] Use file structure instead of Params for LHS menu

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Instead of relying on the `Section` and `Subsection` params which are error prone the LHS now uses the file structure to render the LHS menu.

While touching the code I did some cleanup like removing `.Scratch` and simplifying the code.

I tried to reduce the code duplication, but using a partial is tricky, as there is a lot of context to pass to it. Given that all code is in one file I think it's fine to have the duplication. 

The real changes are in https://github.com/mattermost/mattermost-developer-documentation/commit/b0e5b9487dc0eda361e14e1497d627bb9d7b6b77.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35160

### CODE REVIEW

**Comment by hanzei** [comment]
@lieut-data Requested a review from you as you did the work on https://github.com/mattermost/mattermost-developer-documentation/pull/373 and I don't know about anyone else knowable about Hugo.

**Comment by lieut-data** [comment]
For context:

> Instead of relying on the Section and Subsection params which are error prone the LHS now uses the file structure to render the LHS menu.

Why are these error prone?

**Comment by hanzei** [comment]
@lieut-data It's not obvious for a writer if they got the menu params wrong. E.g. https://developers.mattermost.com/extend/plugins/server/debugging/ is missing them and hence the LHS menue doesn't correctly open

Screenshot from 2021-04-27 09-11-21

I was burned by the same issue recently (fixed in https://github.com/mattermost/mattermost-developer-documentation/pull/800) when I confused ´subsection` with `section`.


The PR also fixed some edge cases where multiple page with the same title would all get highlighted:
Screenshot from 2021-04-27 09-12-46

**Review by lieut-data — APPROVED** [review]
Sweet!

**Comment by hanzei** [comment]
@justinegeffen Could you please do a QA review for the PR and double check that the LHS menu renders correctly on all pages?

**Comment by justinegeffen** [comment]
It looks good to me, thanks Ben!

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
