### PR TITLE
Update rd-teams.md

### PR DESCRIPTION
**Pull request by justinegeffen**
Removed off-boarded team member.

@wiersgallak:
- I wasn't sure whether to add you to Dennis's areas.
- I haven't added Carrie as I wasn't 100% sure where to add her.

### CODE REVIEW

**Comment by wiersgallak** [comment]
@justinegeffen You can add me where Dennis' name is until the position is filled.  Carrie can go on the Core product teams - Core features, Enterprise features, and Cloud features.  Thanks!

**Comment by justinegeffen** [comment]
Thanks, @wiersgallak. Done. :)

**Comment by justinegeffen** [comment]
Gentle reminder on this, @wiersgallak. :)

**Review by wiersgallak — APPROVED** [review]
Thanks, @justinegeffen

**Comment by justinegeffen** [comment]
@grundleborg, is this good to go for this iteration? :)

**Review by grundleborg — APPROVED** [review]

**Pull request merged**
