### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by J35u527**
Updated file to add clear instructions about the installation of a gem called bundler when getting the environment set up

### CODE REVIEW

**Comment by jasonblais** [comment]
Hi @J35u527, thank you for your contribution! Would you be open to completing the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/) and then we'll be good to merge?

If you have any questions, please let us know.

**Comment by J35u527** [comment]
checked cla

**Pull request merged**
