### PR TITLE
Update link for interactive messages

### PR DESCRIPTION
**Pull request by jasonblais**
This shouldn't be merged before v5.4 docs are merged, on or a bit before Oct 16th. But we can review ahead of that.

### CODE REVIEW

**Comment by amyblais** [comment]
The links in the doc don't work, is this expected and they will work after merging the PR?

**Comment by jasonblais** [comment]
@cpanato The build for this PR doesn't appear to pass. Can you help take a look?

Moreover, we seemed to have lost the automatic S3 deployments from mattermost-developer-documentation PRs. That helps check for things like links Amy mentions above. Here's more on it when this was fixed last time: https://pre-release.mattermost.com/core/pl/cnf5fsq67jd5tdtu54m95e4ioo

**Comment by cpanato** [comment]
@jasonblais all fixed

**Comment by jasonblais** [comment]
@amyblais For developer doc PR reviews, if you expand "All checks have passed", then click on "Details" for the "continuous-integration/s3-deploy" line, you'll find a generated developer docs site that contains the changes in this PR.

image

That lets you more easily confirm things like links.

If you have any questions, let me know.

**Comment by jasonblais** [comment]
PS: This PR merged to v5.4 release docs will change the interactive message URL to `../interactive-messages.html`. So I've updated this PR based on that.

https://github.com/mattermost/docs/pull/2315

**Pull request merged**
