### PR TITLE
Rename plugins docs (duplicated) and general editing

### PR DESCRIPTION
**Pull request by justinegeffen**
Removing (Beta) label

### CODE REVIEW

**Review by hanzei — COMMENTED** [review]
There are a lot of places like  https://github.com/mattermost/mattermost-developer-documentation/blob/f02857bb4e3ffb5ac5ef5dc4e7f4ab4e9eb9e485/site/content/integrate/admin-guide/admin-plugins-beta/_index.md#L2-L2  and https://github.com/mattermost/mattermost-developer-documentation/blob/1f39cdf3a5a0d6c1167f1225d4d798b6e5ed8922/site/content/integrate/plugins/_index.md#L12-L12 that also need to get updated. Do you plan to do this as part of this PR?

**Comment by hanzei** [comment]
Is there a corresponding webapp (and maybe server) PR?

**Comment by justinegeffen** [comment]
@hanzei, yep! I just added a second file to this PR and will be reviewing all the content in this repo.

**Comment by justinegeffen** [comment]
> (and maybe server)

No, there isn't. This was based on the fact that there are currently two sections called "Plugins (Beta)" in the LHS. Plugins will be moving to GA but not in this upcoming release so I think we can leave this PR as-is (just changing the headings) and tackle the other work in a separate PR.

**Review by hanzei — APPROVED** [review]
I'm fine to merge this as it is as long there is a ticket to take care of the  rest of the docs.

Should this PR wait until v6.0 is released as there are breaking changes in that release?

**Comment by justinegeffen** [comment]
Awesome. Let's merge this, as it's not actually related to 6.0 so much as a navigation improvement. I've re-added "Beta" to the Plugins one as removing it is only for 6.0.

I've created a card on our board for the full review for 6.0.

Do you have an idea of the breaking changes for the content? I'd like to make a note of them.

**Review by aaronrothschild — APPROVED** [review]
LGTM

**Pull request merged**
