### PR TITLE
Added workflow diagrams

### PR DESCRIPTION
**Pull request by Drishti-jain21**
#### Summary

I have added 3 workflow diagrams to summarize the You've found a bug content under Why-Contribute.

#### Ticket Link

#1143

### CODE REVIEW

**Comment by neflyte** [comment]
Thanks for your contribution, @Drishti-jain21! Please make sure you have signed the [CLA](http://www.mattermost.org/mattermost-contributor-agreement/). :slightly_smiling_face:

**Review by neflyte — APPROVED** [review]

**Comment by neflyte** [comment]
@Drishti-jain21 Could you please include the source to the diagrams so they can be updated in the future should the guidelines change?

Also, you may wish to consider using a MermaidJS diagram which is supported in these docs.

**Comment by Drishti-jain21** [comment]
The diagrams are made upon the content from this page
https://developers.mattermost.com/contribute/why-contribute/#youve-found-a-bug

I am not familiar with MermaidJs and I'll have to redo them again

**Review by azigler — CHANGES_REQUESTED** [review]
@neflyte Status of this one is unclear to me. Are we going to redo these in mermaid to match everything else? I think that would make sense here.

**Review by cwarnermm — APPROVED** [review]
Thank you, @Drishti-jain21!

**Comment by cwarnermm** [comment]
@azigler We're going to publish these great image assets to the developer site as-is knowing that we don't have an easy way to maintain them over time. @neflyte will add a card to the dev docs board to convert the existing image files to Mermaid for ease of maintainability in a future release.

**Comment by cwarnermm** [comment]
@Drishti-jain21 - We will move forward with your PR and merge it into our codebase once you've signed the CLA.

**Comment by Drishti-jain21** [comment]
I have signed the CLA

**Comment by cwarnermm** [comment]
Please try again, @Drishti-jain21.I believe you can check your CLA status by entering ``/check cla`` as a comment to confirm.

**Review by azigler — APPROVED** [review]
Thanks for clarifying @cwarnermm! And thanks @Drishti-jain21 for this PR!

**Pull request merged**
