### PR TITLE
Update iOS env vars

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Remove weird an unnecessary `\` on the environment variable names

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Approving intended changes. A couple of definitions and some consistency issues remain as detailed via https://github.com/mattermost/mattermost-developer-documentation/pull/849

**Comment by enahum** [comment]
Thanks @cwarnermm can I suggest for your team to look into the definition and changes needed?

**Comment by cwarnermm** [comment]
Yes, @enahum. I've logged https://mattermost.atlassian.net/browse/MM-36397 for this work. Thanks!

**Review by justinegeffen — COMMENTED** [review]
I gave this a quick review and added some feedback. Once it's addressed please LMK and I'll give it a second pass.

**Comment by enahum** [comment]
Going to merge this PR and the one for android, any changes required to description, punctuation etc is out of scope. Consider doing a full pass on the docs and submit an overall changes as you see fit as long as the technical meaning remains.

It is very important to understand that this PR is **only** about fixing the environment variables format.

Thank you all for your reviews

**Pull request merged**
