### PR TITLE
Make Go installation step version independant

### PR DESCRIPTION
**Pull request by agnivade**
There was already a text saying "modify installation to latest Go version".
But still the version was hardcoded to 1.13. We change it to a generic version
following the naming at golang.org/dl, to prevent us from having to bump
the version for every new Go release.

### CODE REVIEW

**Comment by grundleborg** [comment]
@justinegeffen adding you to make sure you think the communication is now clear for which go version to install.

**Comment by agnivade** [comment]
ping @justinegeffen

**Comment by justinegeffen** [comment]
Apologies for not reviewing this yet, I've been on PTO and this slipped past me. Thanks for the ping; I am reviewing now.

**Comment by agnivade** [comment]
My apologies. Please enjoy your PTO and come back to this later :)

**Comment by justinegeffen** [comment]
Thanks, @agnivade! During the review I noticed some unrelated items that needed attention, such as minor formatting, so I have added them to this PR.

**Pull request merged**
