### PR TITLE
Move blog out of drafts

### PR DESCRIPTION
**Pull request by jwilander**

### CODE REVIEW

**Comment by jasonblais** [comment]
@jwilander Does this show up in the page nav header?

image

**Comment by jwilander** [comment]
@jasonblais  It takes some time to deploy and for cloudfront caches to expire

**Comment by jwilander** [comment]
But yes it will show up in the header

**Comment by jwilander** [comment]
For some reason it's not deployed yet. Looking into it.

**Comment by jwilander** [comment]
Ok, just needed to invalidate CloudFront and it started showing up

**Comment by jasonblais** [comment]
Sweet! Also working on adding a link somewhere on mattermost.com/blog for discoverability

**Pull request merged**
