### PR TITLE
Fix for sidebar search input styles

### LINKED ISSUE #1203: Search bar not displaying correctly in Firefox 109.0
When using Firefox 109.0 on macOS Ventura 13.1, the search bar isn't displaying correctly. Image provided is an example from https://developers.mattermost.com/integrate/marketplace-submissions/. A spot check confirmed that this is happening on all pages. 

Screenshot 2023-01-26 at 19 28 32

### PR DESCRIPTION
**Pull request by emdecr**
#### Summary
Updates to fix #1203 - the search input breaking out of the sidebar and into the content on Firefox.

### CODE REVIEW

**Comment by cwarnermm** [comment]
I've tested on the following browsers:
- Microsoft Edge Version 109.0.1518.61 (Official build) (arm64) - no issues with search
- Safari on Mac Version 16.2 (18614.3.7.1.5) - no issues with search
- Firefox on Mac 109.0 (64-bit)- no issues with search

**Comment by justinegeffen** [comment]
Works for me on Firefox as well as Chrome 109.0.5414.119. :)

**Comment by cwarnermm** [comment]
Search has an issue when viewed via Edge mobile via iPhone:
IMG_0993

**Comment by cwarnermm** [comment]
Sorry for the absolutely HUGE screenshot, @emdecr! Let me know if there are other browsers/devices you'd like us to test this PR against. Happy to help!

**Comment by emdecr** [comment]
Thanks for the extra eyes and flags @justinegeffen @cwarnermm !
I took a look in Browserstack to replicate and I think it's looking better for all your feedback? Pushed some tweaks.
You might have to hard refresh if it looks like there was no change.

**Review by cwarnermm — APPROVED** [review]
Thank you so much, @emdecr, for this incredibly fast fix!

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
