### PR TITLE
IS-6653: Personal access token docs have outdated screenshots

### PR DESCRIPTION
**Pull request by Rutam21**
## Summary

[Personal Access Token](https://developers.mattermost.com/integrate/reference/personal-access-token/) page has outdated product screenshots which can be very confusing to the users. This PR adds the updated screenshots that align with the latest product and also includes additional screenshots in other sections that missed the visual references.

## Ticket Link

This PR fixes https://github.com/mattermost/docs/issues/6653.

## Checklist

- [x] This PR follows Mattermost Contributing Guidelines.

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes, if any. Thanks.

**Comment by cwarnermm** [comment]
This is a great update, @Rutam21! Thank you!

I'm probably being over-cautious, but I recommend that you hide additional details in the Manage Personal Tokens screenshot. I can _almost_ make out your email address (which you likely don't want visible at all), and I also recommend blurring out some or all of the Token ID.

**Comment by Rutam21** [comment]
@cwarnermm Thanks for the suggestion. I have blurred those details to the maximum extent and updated the screenshot. Also, for safety reasons, I deleted that token after raising the PR.

**Review by cwarnermm — APPROVED** [review]
Thanks, @Rutam21!

**Comment by cwarnermm** [comment]
@amyblais - Looking for a second approval to merge. Thanks!

**Review by amyblais — APPROVED** [review]

**Comment by amyblais** [comment]
@cwarnermm Approved!

**Pull request merged**
