### PR TITLE
Updated deprecated links in admin-slash-commands _index.md

### PR DESCRIPTION
**Pull request by Rutam21**
#### Summary

Updated deprecated links in the admin-slash-commands  _index.md

#### Ticket Link

NA

### CODE REVIEW

**Comment by Rutam21** [comment]
@cwarnermm Please review and suggest changes if any and also add the appropriate labels for Docathon.

**Review by justinegeffen — COMMENTED** [review]
Thank you for this PR! :)

**Review by justinegeffen — COMMENTED** [review]
Thank you for your PR! I left some feedback and suggestions.

**Comment by Rutam21** [comment]
@justinegeffen Changes are applied. Please review.

**Review by justinegeffen — APPROVED** [review]
Thank you! This looks good to me. :)

**Review by cwarnermm — APPROVED** [review]
Thank you for your docs contribution!

**Pull request merged**
