### PR TITLE
Tweak spacing in responsive layout files for mobile

### PR DESCRIPTION
**Pull request by tnir**
#### Summary

Tweaks many spacing in responsive layout files mainly for mobile to reduce unexpected horizontal drifts on mobile screens.

This PR also helps developer experience by replacing home-made CSS selectors with Bootstrap 4's utilities.

#### Ticket Link

This change is a groundwork for Hugo layouts and not relevant to any specific feature(s).

### CODE REVIEW

**Comment by tnir** [comment]
@cwarnermm Thoughts?

**Comment by cwarnermm** [comment]
update-branch

**Comment by tnir** [comment]
update-branch

**Comment by tnir** [comment]
update-branch @cwarnermm

**Comment by cwarnermm** [comment]
@emdecr - Are you open to taking a peek at this dev docs PR, please? I'd love to get your input on the proposed changes.

**Comment by emdecr** [comment]
@cwarnermm Sure thing - will circle back within the next day or so.

**Review by emdecr — APPROVED** [review]
@cwarnermm These standardizations make sense to me 👍 
Looking around they don't seem to break anything.

**Review by cwarnermm — APPROVED** [review]
Thank you again, @tnir, for your patience on this docs PR.

**Comment by tnir** [comment]
Thanks @cwarnermm. This change carried me a nice mobile experience on dev guide indeed 🎉

**Pull request merged**
