### PR TITLE
add ops/infra team

### PR DESCRIPTION
**Pull request by cpanato**

### CODE REVIEW

**Comment by hanzei** [comment]
@jwilander Gentle reminder to review this

**Comment by jwilander** [comment]
Thanks @hanzei, I'm purposefully holding off on this one as it's not an "official" team yet. Just something we're trying out to see how it goes

**Comment by hanzei** [comment]
I see. Thanks for the explanation and sorry for the poke. Added "Do Not Merge" to mark the state of this PR.

**Comment by jwilander** [comment]
No worries :)

**Pull request merged**
