### PR TITLE
Update incoming webhook response parameters

### PR DESCRIPTION
**Pull request by neflyte**
#### Summary

This PR fixes incorrect information about responses to Incoming Webhooks with regard to the `username` and `icon_url` properties. Contrary to the existing docs, the `username` and `icon_url` properties will not inherit their values from the user who created the incoming webhook.

### CODE REVIEW

**Review by azigler — COMMENTED** [review]
Looks good to me, if this is the case. Do these potentially have different values depending on if `Enable integrations to override usernames` et al are enabled via the System Console?

**Comment by jprusch** [comment]
It should be mentioned, that if no username / icon is set in the webhook configuration dialog, it defaults to "webhook" and the default webhook image.

**Review by levb — APPROVED** [review]

**Review by cwarnermm — APPROVED** [review]
Thanks, @neflyte!

**Comment by neflyte** [comment]
@azigler Yes, they will default to the name `webhook` and the standard webhook icon. The doc doesn't call this out clearly, though. :slightly_smiling_face: I'll fix that up!

**Comment by neflyte** [comment]
@jprusch Thanks! I will add that detail. :slightly_smiling_face:

**Comment by neflyte** [comment]
I made similar changes to the Outgoing Webhooks page as well. :)

**Review by azigler — APPROVED** [review]
Thanks for clarifying @neflyte!

**Pull request merged**
