### PR TITLE
Update Bootstrap from 4.0.0-beta.2 to 4.6.2

### LINKED ISSUE #1360: Update Bootstrap from 4.0.0-beta.2 to 4.x (latest) (4.6.2)
- Follows up #43
- https://getbootstrap.com/docs/4.6/getting-started/download/

### PR DESCRIPTION
**Pull request by tnir**
- Closes #1360
- Updates #43

#### Summary

Updates Bootstrap CSS from 4.0.0-beta.2 to 4.6.2.

Note: `https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js` has not been used since #43 for 6+ years.

#### Checklist

- [x] ` diff -u <(curl -sSL https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css) site/static/css/bootstrap.min.css; echo $?` should output only `0` without any diff lines.

#### Ticket Link

- #1360

### CODE REVIEW

**Comment by tnir** [comment]
@ccbrown Thoughts?

**Comment by tnir** [comment]
@cwarnermm How can I help you get this merged?

**Comment by tnir** [comment]
@cwarnermm What do you think?

**Comment by tnir** [comment]
@cwarnermm How can I help you?

**Review by cwarnermm — APPROVED** [review]
Thank you, @tnir, for your code contribution to the Mattermost Developer Documentation, your patience as we review your PR, and your friendly reminders along the way. All appreciated.

**Review by M-ZubairAhmed — APPROVED** [review]
This looks good :shipit: Thank you

**Pull request merged**
