### PR TITLE
Updated dev docs banner for Feb 16 webinar

### PR DESCRIPTION
**Pull request by cwarnermm**

### CODE REVIEW

**Comment by azigler** [comment]
@cwarnermm Was this copy provided by Erin Larsen? I just wanted to know where the request to change this came from and if it came with copy or if you wrote it yourself. I can sync with Erin to confirm this is good, if needed!

**Comment by cwarnermm** [comment]
I wrote the copy myself, @azigler. And good reminder about providing enough context for reviewers to know why a change is being made :)

I initiated a discussion in the Marketing channel on the Mattermost Community Server about updating the docs banners, and Elli L provided this great idea. I applied the same style as a recent similar Webinar banner announcement whose copy was provided by Marketing.

**Review by azigler — APPROVED** [review]
@cwarnermm I worked with Erin to finalize the copy on this and it's now ready to merge. Thanks for tackling this! Erin can provide the initial copy moving forward when webinar banners are added. 😎

**Comment by cwarnermm** [comment]
Fantastic, thanks, @azigler!

**Comment by azigler** [comment]
@cwarnermm @emdecr Erin is ready for these to go live once these are approved and merged. This is her approved copy and link. Thanks!

**Review by emdecr — APPROVED** [review]
All looks good on my end. Thanks folks!

**Pull request merged**
