### PR TITLE
Fix quoting issue

### PR DESCRIPTION
**Pull request by metanerd**
#### Summary
There is an issue with quoting. This should fix it. 

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/518

### CODE REVIEW

**Comment by hanzei** [comment]
@metanerd Should the pipeline of the failing builds in the past should be run again?

**Comment by metanerd** [comment]
@hanzei just the notification failed. The deploy was completed.

**Comment by hanzei** [comment]
Should the notifications be re-send?

**Comment by metanerd** [comment]
We have to do it manually, since the script gets the information from the PR which adds the new blog entry. https://github.com/mattermost/mattermost-developer-documentation/blob/bfb3fb0dfc3473ac9a413e49d12db78a2e00f0dc/.github/workflows/notify-mm-blog.yml#L19
:(

**Comment by hanzei** [comment]
@metanerd There is still something fishy going on. I did re-run a pipeline to re-send the notification, but it exited with: `mattermost.json is empty exiting without failing.` despite `mattermost.json` containing the correct payload. See https://github.com/mattermost/mattermost-developer-documentation/runs/528500487?check_suite_focus=true

**Comment by hanzei** [comment]
> @metanerd There is still something fishy going on. I did re-run a pipeline to re-send the notification, but it exited with: `mattermost.json is empty exiting without failing.` despite `mattermost.json` containing the correct payload. See https://github.com/mattermost/mattermost-developer-documentation/runs/528500487?check_suite_focus=true

I found the bug. https://github.com/mattermost/action-mattermost-notify/pull/6 to fix it

**Pull request merged**
