### PR TITLE
Hugo cleanup

### PR DESCRIPTION
**Pull request by neflyte**
#### Summary

A cleanup of Hugo and its files, consisting of:
- Removing unused templates found using the `--printUnusedTemplates` parameter
- Removing extraneous data in the `themes/` directory
- Upgrading Hugo from 0.92.1 to 0.101.0 in the build pipeline

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thanks, @neflyte!

**Comment by cwarnermm** [comment]
@pfltdv - This PR will have an impact on our build pipelines for the dev docs. Would you be open to reviewing this PR, please?

**Review by pfltdv — APPROVED** [review]
Thanks alot @neflyte.

**Comment by pfltdv** [comment]
> @pfltdv - This PR will have an impact on our build pipelines for the dev docs. Would you be open to reviewing this PR, please?

@cwarnermm No other change is needed to upgrade Hugo at pipelines and pipelines are working after Hugo upgrade.

**Review by emdecr — APPROVED** [review]
Thanks for your patience folks + thanks @neflyte for the edits. Pulled your changes and everything looks good. Clicked around to test and it doesn't seem like the deletion of the legacy partials are breaking things.

---

Looking at the site also reminds me that I can probably submit another PR to sync the nav on this site (and docs.mm.com) with mm.com. We might be making tweaks to the menu in the near future, so might do a completely overhaul once that is complete. cc @cwarnermm

**Pull request merged**
