### PR TITLE
Remove excess `<br>`

### PR DESCRIPTION
**Pull request by ckaznable**
#### Summary

I found extra `<br>`characters in document

### CODE REVIEW

**Comment by cwarnermm** [comment]
@enahum - Please confirm that `<br>` should be removed in these specific instances.

**Review by enahum — COMMENTED** [review]
The idea behind this was to create a split in the name of the envs, not sure is extra. Please do confirm by looking at the rendered page

**Comment by ckaznable** [comment]
I can find these variables without `<br>` in these codes

https://github.com/mattermost/mattermost-mobile/blob/main/fastlane/env_vars_example#L39

https://github.com/mattermost/mattermost-mobile/blob/main/fastlane/env_vars_example#L62

https://github.com/mattermost/mattermost-mobile/blob/main/fastlane/Fastfile#L104

https://github.com/mattermost/mattermost-mobile/blob/main/fastlane/.env.ios.release#L19

**Comment by enahum** [comment]
> I can find these variables without `<br>` in these codes
> 
> 
> 
> https://github.com/mattermost/mattermost-mobile/blob/main/fastlane/env_vars_example#L39
> 
> 
> 
> https://github.com/mattermost/mattermost-mobile/blob/main/fastlane/env_vars_example#L62
> 
> 
> 
> https://github.com/mattermost/mattermost-mobile/blob/main/fastlane/Fastfile#L104
> 
> 
> 
> https://github.com/mattermost/mattermost-mobile/blob/main/fastlane/.env.ios.release#L19
> 
> 
> 
> 

There is a difference in how they are shown in the documentation for reading purposes, <br> in the webpage was suppoused to create a new line and not show the actual <br> string in the name of the environment variable but it seems that is no longer the case.

Will approve the PR

**Review by enahum — APPROVED** [review]

**Review by cwarnermm — APPROVED** [review]
Thank you, @ckaznable! Great catch!

**Pull request merged**
