### PR TITLE
Remove storybook step from local e2e setup

### PR DESCRIPTION
**Pull request by AshishDhama**
#### Summary
We have removed the storybook from the mattermost-webapp, so this step isn't required anymore.
Confusing for new contributors.
https://community.mattermost.com/core/pl/j6jx6c9oapggdezs31dukkmfry

#### Ticket Link
NA

### CODE REVIEW

**Comment by cwarnermm** [comment]
Thank you for this PR, @AshishDhama! The Developer documentation includes the following additional references to ``storybook`` that may need to be changed or removed as well:
- https://developers.mattermost.com/contribute/more-info/mobile/storybook/ - should this page be available given the tooling change?
- https://developers.mattermost.com/contribute/more-info/webapp/e2e/running-e2e/ contains a few more `storybook` references to review and address
- https://developers.mattermost.com/contribute/more-info/webapp/e2e-cheatsheet/basic-code-structure/ - contains 1 reference to `storybook` to review and address. CC @saturninoabril 

@AshishDhama - May I get your help with one additional thing, please? I noticed that the last 2 documentation pages above aren't easy to access. They're not visible in the navigation pane, and related docs pages don't include links to these pages. Would you be open to adding links to these 2 pages from a related docs page? Doing so would help future readers find this important content more easily.

For example:
- the running-e2e page could be a link from the e2e page
- the basic-code-structure page could be a link from the e2e cheatsheet

The Docs team is investigating ways to expand the navigation pane to show more granular levels of detail too.

**Comment by saturninoabril** [comment]
Thanks @AshishDhama and good catch @cwarnermm! I agree with the comments except for the storybook with the mobile as I believe it's being used.

**Comment by AshishDhama** [comment]
@cwarnermm Yeah sure.

**Comment by cwarnermm** [comment]
@saturninoabril - It's just storybook for webapp that's changing, correct?

**Comment by saturninoabril** [comment]
That's correct @cwarnermm.

**Comment by cwarnermm** [comment]
@AshishDhama - As discussed on the Mattermost Community Server, access to some dev docs pages is a known gap that the Docs team will address in a future iteration. Thank you so much for being so open and willing to help, though -- very much appreciated!

**Review by cwarnermm — APPROVED** [review]

**Pull request merged**
