### PR TITLE
[Docs]: Updating Label

### LINKED ISSUE #618: Request for Documentation: Document Test Server labels
Mattermost user `hanzei` from https://community.mattermost.com has requested the following be documented:

```
Did the Could Test Server always been an EE server without a license? I swear they used to also include a license. 
```

See the original post [here](https://community.mattermost.com/_redirect/pl/hjrneszpmjra5qgnj47w7q7kmh).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

### PR DESCRIPTION
**Pull request by Sonichigo**
#### Summary
Fix #618 

Setup Cloud Test Server label triggers the creation of an Enterprise Edition test server and not just Test Server

### CODE REVIEW

**Review by spirosoik — APPROVED** [review]

**Comment by hanzei** [comment]
@gabrieljackson Could you please give this PR a review when you have the time?

**Review by gabrieljackson — COMMENTED** [review]
LGTM. Thanks for this. 👍

**Review by gabrieljackson — APPROVED** [review]

**Pull request merged**
