### PR TITLE
Update developer-setup.md

### PR DESCRIPTION
**Pull request by dontoisme**
Updated path to webapp folder to run`nvm install`

### CODE REVIEW

**Comment by dontoisme** [comment]
By the way, we can now remove the 
` cd mattermoset-webapp` in step 7

**Comment by dontoisme** [comment]
One more thing to note: if the mattermost-server is not running (step 7 in https://developers.mattermost.com/contribute/server/developer-setup/) then step 8 will fail. 

I propose adding a new step after 7 that links back to the developer-setup page as well as has instructions to open a new terminal session and cd'ing into mattermost-server and doing `make run-server`.

**Comment by neflyte** [comment]
Thanks for the contribution, @dontoisme!
Feel free to make the other changes you suggested in this PR; they sound good to me. :smile:

**Review by neflyte — APPROVED** [review]

**Review by M-ZubairAhmed — APPROVED** [review]

**Comment by cwarnermm** [comment]
@dontoisme - I've applied your feedback. Thank you! Really appreciate the thorough, hands-on documentation updates!

The malformed link you identified is present in all of the final step of all OS setup steps to the Web App Developer Setup. I'm able to reproduce this locally, but the link follows our standard convention. I'll see if my commit generates a new preview that shows the links working to rule out whether it's simply a caching issue, and investigate further if needed.

**Review by cwarnermm — APPROVED** [review]

**Pull request merged**
